project_id = "fdwaufhnkrqbbxmdmxjf"

[functions.get-orders-by-promo]
verify_jwt = false

[functions.preview-transactional-email]
verify_jwt = false


[functions.newsletter-confirm]
verify_jwt = false
